AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  CertificateArn:
    Type: String
    Description: ARN of the certificate for the API Gateway Custom Domain

Resources:
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitorCount
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: visitor_count.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorCountTable
      Events:
        VisitorCountAPI:
          Type: Api
          Properties:
            Path: /visitor-count
            Method: get
      Policies:
      - AmazonDynamoDBFullAccess

  VisitorCountAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Domain:
        DomainName: "cloud-resume-api.cmelgreen.com"
        CertificateArn: !Ref CertificateArn
        Route53:
          HostedZoneName: "cmelgreen.com"
          EvaluateTargetHealth: false
          DistributionDomainName: "cloud-resume-api.cmelgreen.com"
        BasePath:
        - visitor-count
      DefinitionBody:
        swagger: '2.0'
        paths:
          /visitor-count:
            get:
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VisitorCountFunction.Arn}/invocations"