on:
  push:
    paths:
      - frontend/**
      - .github/workflows/s3-deploy.yaml

jobs:
  deploy:
    name: Deploy Static Site to S3
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Environment Variables
      id: dotenv
      uses: falti/dotenv-action@v1.0.2
      with:
        path: ./terraform/project.auto.tfvars

    - name: Check vars
      run: |
        echo ${{ steps.dotenv.outputs.PROJECT_NAME }}
        echo ${{ steps.dotenv.outputs.AWS_REGION }}

    - name: Assume Lambda Admin Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ steps.dotenv.outputs.PROJECT_NAME }}
        aws-region: ${{ steps.dotenv.outputs.AWS_REGION }}

    - name: Upload frontend
      run: |
        aws s3 sync ./frontend s3://${{ steps.dotenv.outputs.PROJECT_OWNER }}-${{ steps.dotenv.outputs.PROJECT_NAME}}/frontend 