on:
  push:
    paths:
      - backend/**
      - .github/workflows/sam-stack-deploy.yaml

jobs:
  build-deploy:      
    name: Deploy SAM Stack  
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get Environment Variables
      id: dotenv
      uses: falti/dotenv-action@v1.0.2
      with:
        path: ./terraform/project.auto.tfvars

    - name: Assume AWS Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ steps.dotenv.outputs.PROJECT_NAME }}
        aws-region: ${{ steps.dotenv.outputs.AWS_REGION }}
      
    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Setup SAM
      uses: aws-actions/setup-sam@v1

    - name: Build SAM stack
      working-directory: ./backend
      run: sam build --use-container

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      working-directory: ./backend
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      working-directory: ./backend
      run: |
        pytest

    - name: Deploy SAM stack
      working-directory: ./backend
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --resolve-s3 --parameter-overrides CERTIFICATE_ARN=${{ secrets.CERTIFICATE_ARN }} --stack-name ${{ steps.dotenv.outputs.PROJECT_NAME }} --region ${{ steps.dotenv.outputs.AWS_REGION }} 

