on:
  push:
    paths:
      - backend/**

jobs:
  build-deploy:
    defaults:
      run:
        working-directory: ./backend
        
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Environment Variables
      id: dotenv
      uses: falti/dotenv-action@v1.0.2
      with:
        dotenv-file: ../terraform/project.auto.tfvars

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Setup SAM
      uses: aws-actions/setup-sam@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ steps.dotenv.outputs.AWS_REGION }}
        aws-region: ${{ steps.dotenv.outputs.AWS_REGION }}

    - name: Build SAM stack
      run: sam build --use-container

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

    - name: Deploy SAM stack
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ steps.dotenv.outputs.PROJECT_NAME }} --region ${{ steps.dotenv.outputs.AWS_REGION }} 

